#!/usr/bin/env bash
set -euo pipefail

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

fix=""
if [ ! -n "${GITHUB_ACTIONS}" ]; then
  fix="--fix"
fi

MOUNTOPTION=""
if [ "$(uname -s)" = "Darwin" ]; then
  MOUNTOPTION=":delegated"
fi

set -x
docker run -t --rm \
  -v "${ROOT}":/app${MOUNTOPTION} \
  -w /app \
  -e CGO_ENABLED=0 \
  -e GOCACHE=/app/.cache \
  golangci/golangci-lint:v1.56.2 \
  golangci-lint run --verbose --timeout=10m ${fix}
