name: Go

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
      id: go-changes
      with:
        files: |
          cmd/**
          internal/**
          vendor/**
          go.mod
          go.sum

    - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      if: steps.go-changes.outputs.any_changed == 'true'
      id: go-cache
      with:
        key: main-gocache
        path: |
          .cache

    - name: Lint
      if: steps.go-changes.outputs.any_changed == 'true'
      run: ./script/lint