name: Build Docker Image
on:
    push:
        branches:
        - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        file: Dockerfile
        tags: robbydyer/namerouter:${{ github.sha }},robbydyer/namerouter:latest
        platforms: linux/amd64